/**
 * Agent Types
 *
 * Request/response types for all agents
 */

import { PersonProfile, ProjectProfile } from './profile';
import { ChatMessage } from './conversation';

// Workflow types
export type WorkflowType = 'CREATE_TWIN' | 'CREATE_PROJECT' | 'CHAT' | 'UPDATE_PROFILE';

// Base agent response
export interface AgentResponse<T = unknown> {
  success: boolean;
  agent: string;
  output: T;
  executionTime: number;
  error?: string;
}

// Coordinator Agent
export interface CoordinatorRequest {
  message: string;
  // Full interview transcript so far, forwarded to the Interview Agent when the
  // Coordinator routes to CREATE_TWIN / CREATE_PROJECT / UPDATE_PROFILE.
  messages?: Array<{ role: 'agent' | 'user'; content: string }>;
  // Set once a caller already knows it's continuing an active interview
  // (e.g. useInterview on turn 2+). The Coordinator's own classification
  // still runs every turn, but this hint wins over it in postProcess() --
  // a free-text interview answer is not reliably classifiable in isolation,
  // even given the full transcript (see DECISIONS.md #007).
  activeWorkflow?: 'CREATE_TWIN' | 'CREATE_PROJECT';
  // Forwarded to the Interview Agent unchanged -- see InterviewRequest.
  collectedFields?: Record<string, string | string[]>;
  context?: {
    twinId?: string;
    projectId?: string;
  };
  // Invoked synchronously as the CHAT workflow's pipeline actually
  // progresses (Decision starting, Review starting, pipeline complete) --
  // lets a caller (e.g. useChat) drive live UI state instead of guessing
  // timings. The Coordinator's own classification stage isn't reported here
  // since the caller already knows it's about to call execute(). Ignored
  // for non-CHAT workflows.
  onStageChange?: (stage: 'decision' | 'review' | 'complete') => void;
}

// Raw classification output validated against the Coordinator's own LLM call.
export interface CoordinatorResponse {
  workflow: WorkflowType;
}

// Final result returned by CoordinatorAgent.execute() after it orchestrates the
// agent(s) selected by the classified workflow. Richer than CoordinatorResponse
// because the LLM only classifies — the Coordinator's postProcess() does the rest.
export type CoordinatorResult =
  | { workflow: 'CREATE_TWIN' | 'CREATE_PROJECT' | 'UPDATE_PROFILE'; interview: InterviewResponse }
  | { workflow: 'CHAT'; decision: DecisionResponse; review: ReviewResponse };

// Context assembled by Middleware before an agent that needs it executes.
// Agents read from this; they never fetch it themselves.
export interface AgentContext {
  personProfile?: PersonProfile;
  projectProfile?: ProjectProfile;
  conversationHistory?: ChatMessage[];
}

// Interview Agent
export interface InterviewRequest {
  type: 'personal' | 'project';
  messages: Array<{ role: 'agent' | 'user'; content: string }>;
  twinId?: string; // For project interviews
  // Fields collected so far, code-maintained by the caller (see useInterview)
  // and merged with each turn's extraction inside InterviewAgent. Passing
  // this back every turn means the LLM only ever has to extract from the
  // latest answer, not re-derive the whole profile from the transcript.
  collectedFields?: Record<string, string | string[]>;
}

export interface InterviewResponse {
  complete: boolean;
  nextQuestion?: string;
  // 3-5 short quick-reply options for nextQuestion, when present.
  suggestions?: string[];
  // The full, normalized, accumulated field state -- the caller should
  // REPLACE its stored collectedFields with this each turn, not merge it,
  // so a value normalized this turn is never re-corrupted by a stale
  // un-normalized copy carried forward from an earlier turn.
  collectedFields?: Record<string, string | string[]>;
  // Only present once `complete` is true -- assembled by code from
  // already-validated collectedFields, never re-generated by the LLM in one
  // shot. See DECISIONS.md on why the previous design was unreliable.
  profile?: PersonProfile | ProjectProfile;
  missingFields?: string[];
  // The twin this profile belongs to -- present once the personal stage
  // completes and saves, so the caller can chain into the project stage.
  twinId?: string;
  progress?: { collected: number; total: number };
}

// Decision Agent
// conversationHistory/personProfile/projectProfile are NOT here — they arrive
// exclusively via AgentContext, assembled by Middleware before execute() runs.
export interface DecisionRequest {
  question: string;
  twinId: string;
  projectId: string;
}

export interface DecisionResponse {
  answer: string;
  reasoning: string[];
  confidence: number;
}

// Review Agent
// personProfile/projectProfile are NOT here — same AgentContext passed to Decision.
export interface ReviewRequest {
  decision: DecisionResponse;
}

export interface ReviewResponse {
  approved: boolean;
  confidence: number;
  requiresHuman: boolean;
  reason?: string;
}

// Agent execution state (for UI visualization)
export type AgentExecutionState = 'idle' | 'coordinator' | 'decision' | 'review' | 'complete' | 'error';

export interface AgentExecutionStatus {
  state: AgentExecutionState;
  currentAgent?: string;
  progress: number; // 0-100
  message?: string;
}
